### ISSUE TITLE
Full use cases defined

### ISSUE THREAD

**Issue by Fraser83** [gabriel-napier/SoftEngGroup2#61]
As a developer I can create use cases so that I can see list of actions or event steps defining the interactions between a user and the system to achieve a goal.

Tasks
Add a folder to the project called "use-cases"
Add at least one use-case in .Markdown langues using below template as a guide

https://github.com/Kevin-Sim/SET08103/blob/master/labs/lab05/use-case-4.md

**Comment by FraserMacL** [comment]
https://github.com/gabriel-napier/SoftEngGroup2/pull/62
